# .github/workflows/scheduled-builds.yml
name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Send Comics
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl --location --request POST 'http://ec2-54-242-189-143.compute-1.amazonaws.com/mail_comic.php' --form 'auth="admincansendmail"'